export const amenities = [
    "In-Unit Laundry",
    "Central Heat",
    "A/C",
    "Dishwasher",
    "Washer/Dryer",
    "Fireplace",
    "Pool",
    "Hot Tub",
    "Private Outdoor Space",
    "Parking",
    "Elevator Entrance",
    "Water View",
    "Skyline View",
    "Park View",
    "Mountain View",
    "Smoke Alarm",
    "Carbon Monoxide Alarm",
    "Private Gym",
    "Dedicated Workspace",
    "Hardwood Floors",
    "Lots of Natural Light",
  ];